/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import components.ChatBody;
import components.ChatBottom;
import components.ChatTitle;
import event.PublicEvent;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ORANGEBD
 */
public class Chat extends javax.swing.JPanel {

    /**
     * Creates new form Right_Menu
     */
    public Chat() {
        initComponents();
//        init();
    }
    
//    private void init() {
//        setLayout(new MigLayout("fillx", "0[fill]0", "0[]0[100%, bottom]0[shrink 0]0"));
//        ChatTitle chatTitle = new ChatTitle();
//        ChatBody chatBody = new ChatBody();
//        ChatBottom chatBottom = new ChatBottom();
////        PublicEvent.getInstance().addEventChat(new EventChat() {
////            @Override
////            public void sendMessage(String text) {
////                chatBody.addItemRight(text);
////            }
////        });
//        add(chatTitle, "wrap");
//        add(chatBody, "wrap");
//        add(chatBottom, "h ::50%");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatBody1 = new components.ChatBody();
        chatFooterBottom = new components.ChatBottom();
        chatDetailsBody = new components.ChatBody();
        chatTitle2 = new components.ChatTitle();

        setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout chatFooterBottomLayout = new javax.swing.GroupLayout(chatFooterBottom);
        chatFooterBottom.setLayout(chatFooterBottomLayout);
        chatFooterBottomLayout.setHorizontalGroup(
            chatFooterBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chatFooterBottomLayout.setVerticalGroup(
            chatFooterBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatFooterBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chatDetailsBody, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(chatTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chatTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chatDetailsBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chatFooterBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.ChatBody chatBody1;
    private components.ChatBody chatDetailsBody;
    private components.ChatBottom chatFooterBottom;
    private components.ChatTitle chatTitle2;
    // End of variables declaration//GEN-END:variables
}
