/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import components.Person_List;
import event.EventMenuLeft;
import event.PublicEvent;
import java.util.ArrayList;
import java.util.List;
import model.Model_User_Account;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ORANGEBD
 */
public class Left_Menu extends javax.swing.JPanel {

    /**
     * Creates new form Right_Menu
     */
    
    private List<Model_User_Account> userAccount;
    
    public Left_Menu() {
        initComponents();
        init();
    }
    
    private void init(){
        chatList.setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
        userAccount = new ArrayList<>();
        PublicEvent.getInstance().addEventMenuLeft(new EventMenuLeft() {
            @Override
            public void newUser(List<Model_User_Account> users) {
                for (Model_User_Account d : users) {
                    userAccount.add(d);
                    chatList.add(new Person_List(d.getUserName()), "Wrap");
                    refreshChatList();
                }
            }
        });
        showPersonList();
    }
    
    private void showPersonList(){
        chatList.removeAll();
        for (Model_User_Account d : userAccount) {
            chatList.add(new Person_List(d.getUserName()), "wrap");
        }
        refreshChatList();
    }
    
    
    private void showGroupList(){
        chatList.removeAll();
        for(int i=0; i<5; i++){
            String group = "Group-"+(i+1);
            chatList.add(new Person_List(group), "Wrap");
        }
        refreshChatList();
    }
    
    
    private void showBoxList(){
        chatList.removeAll();
        for(int i=0; i<10; i++){
            String box = "Box-"+(i+1);
            chatList.add(new Person_List(box), "Wrap");
        }
        refreshChatList();
    }
    
    private void refreshChatList(){
        chatList.repaint();
        chatList.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftMenuLayout = new javax.swing.JLayeredPane();
        messageButton = new javax.swing.JButton();
        groupMSGButton = new javax.swing.JButton();
        boxMSGButton = new javax.swing.JButton();
        sp = new javax.swing.JScrollPane();
        chatList = new javax.swing.JLayeredPane();

        LeftMenuLayout.setBackground(new java.awt.Color(246, 246, 246));
        LeftMenuLayout.setLayout(new java.awt.GridLayout(1, 3));

        messageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/message.png"))); // NOI18N
        messageButton.setBorder(null);
        messageButton.setBorderPainted(false);
        messageButton.setContentAreaFilled(false);
        messageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messageButton.setSelected(true);
        messageButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/message_selected.png"))); // NOI18N
        messageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageButtonActionPerformed(evt);
            }
        });
        LeftMenuLayout.add(messageButton);

        groupMSGButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        groupMSGButton.setBorder(null);
        groupMSGButton.setBorderPainted(false);
        groupMSGButton.setContentAreaFilled(false);
        groupMSGButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        groupMSGButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_selected.png"))); // NOI18N
        groupMSGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMSGButtonActionPerformed(evt);
            }
        });
        LeftMenuLayout.add(groupMSGButton);

        boxMSGButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/box.png"))); // NOI18N
        boxMSGButton.setBorder(null);
        boxMSGButton.setBorderPainted(false);
        boxMSGButton.setContentAreaFilled(false);
        boxMSGButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxMSGButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/box_selected.png"))); // NOI18N
        boxMSGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMSGButtonActionPerformed(evt);
            }
        });
        LeftMenuLayout.add(boxMSGButton);

        sp.setBackground(new java.awt.Color(249, 249, 249));

        chatList.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout chatListLayout = new javax.swing.GroupLayout(chatList);
        chatList.setLayout(chatListLayout);
        chatListLayout.setHorizontalGroup(
            chatListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chatListLayout.setVerticalGroup(
            chatListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        sp.setViewportView(chatList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftMenuLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(sp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeftMenuLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageButtonActionPerformed
        if(!messageButton.isSelected()){
            messageButton.setSelected(true);
            groupMSGButton.setSelected(false);
            boxMSGButton.setSelected(false);
            showPersonList();
        }
    }//GEN-LAST:event_messageButtonActionPerformed

    private void groupMSGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupMSGButtonActionPerformed
        if(!groupMSGButton.isSelected()){
            messageButton.setSelected(false);
            groupMSGButton.setSelected(true);
            boxMSGButton.setSelected(false);
            showGroupList();
        }
    }//GEN-LAST:event_groupMSGButtonActionPerformed

    private void boxMSGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMSGButtonActionPerformed
        if(!boxMSGButton.isSelected()){
            messageButton.setSelected(false);
            groupMSGButton.setSelected(false);
            boxMSGButton.setSelected(true);
            showBoxList();
        }
    }//GEN-LAST:event_boxMSGButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LeftMenuLayout;
    private javax.swing.JButton boxMSGButton;
    private javax.swing.JLayeredPane chatList;
    private javax.swing.JButton groupMSGButton;
    private javax.swing.JButton messageButton;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
